Make events default rly start method
strangelove-ventures/ibctest pull request #253
Opened 2022-08-17 21:42 UTC by jtieri

## Description

This PR makes the `-p events` flag the default method for starting `rly`.

I kept running the tests consecutively and without adding a slightly greater initial block history the tests were failing intermittenly.

## Checklist

- [ ] I have made sure the upstream branch for this PR is correct
- [ ] I have made sure this PR is ready to merge
- [ ] I have made sure that I have assigned reviewers related to this project

2022-08-17 21:52 UTC, DavidNix approved these changes

2022-08-17 22:30 UTC, mark-rushakoff requested changes
I would prefer to see this as a separate relayer implementation, for now. Otherwise this makes it impossible to test the legacy implementation, doesn't it?

2022-08-17 22:40 UTC, jtieri commented
Hmm looks like the `TestPacketForwardMiddleware` is failing and looks like it has to do with some contention in trying to start two relayer processes for the two paths required in this test. I wasn't noticing it on my local machine because I was skipping the test with `--short`. After fiddling with it for the last hour or so it seems to be a more involved fix.

2022-08-17 22:42 UTC, jtieri commented
> I would prefer to see this as a separate relayer implementation, for now. Otherwise this makes it impossible to test the legacy implementation, doesn't it?

That is correct but iirc we had discussed it internally and agreed that because we are still testing the legacy implementation in the `relayer` repo's CI that this would be acceptable. It does seem like, however, this may require some additional work at this point to get more than one relayer instance working or to get one relayer instance relaying on multiple paths.

2022-08-17 22:57 UTC, mark-rushakoff commented
That’s fair, you can dismiss my review. A comment near the added flag would
be helpful though.

On Wed, Aug 17, 2022 at 6:42 PM Justin Tieri ***@***.***>
wrote:

> I would prefer to see this as a separate relayer implementation, for now.
> Otherwise this makes it impossible to test the legacy implementation,
> doesn't it?
>
> That is correct but iirc we had discussed it internally and agreed that
> because we are still testing the legacy implementation in the relayer
> repo's CI that this would be acceptable. It does seem like, however, this
> may require some additional work at this point to get more than one relayer
> instance working or to get one relayer instance relaying on multiple paths.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/strangelove-ventures/ibctest/pull/253#issuecomment-1218563866>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACG6VYVIR5OQMCPQUK5KDLVZVTE7ANCNFSM563A35CA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-09-19 19:44 UTC, jtieri commented
This is the default behavior in the relayer now, so no need to explicitly set this after #295

2022-09-19 19:44 UTC, closed without merging